### ISSUE TITLE
New account creation, login, and guest/demo login - Review

### ISSUE THREAD

**Issue by skp96** [skp96/Littlehood#2]
Users can sign up, login, and logout
Users can use a demo login to try the site
Users can't use certain features without logging in (creating a watchlist, seeing portfolio performance)

--- Haven't created a demo login yet, since there isn't a user page set up yet.

**Comment by skp96** [comment]
Ready to be checked

**Comment by jliversi** [comment]
Hey Sunny, great progress overall, but definitely a few things that need changing. 

- [ ] Integrate the demo user. Even though you don't yet have a user page, this is a vital part of user_auth, and is simple as seeding a single user and having a button which shoots of a login with that seeded user's data.
- [ ] Your styling currently pretty approximate and a lot of your spacing/font-size need to be adjusted. 
- [ ] There are still debuggers in your code. Remove all debuggers before heroku pushes.
- [ ] When signing up, any errors cause your site to break and get a 500 internal service error. (Your errors on your login form are perfect though).
